### ISSUE TITLE
Installing the package

### ISSUE THREAD

**Issue by thuvousc** [ethanbass/chromatographR#21]
Hi,

I cannot install the package even though I tried both three ways recommended.

> install.packages("chromatographR")
Installing package into 'C:/Users/ttmvo/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)
Warning in install.packages :
  package 'chromatographR' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Could you please address which version of R has this package "chromatograph"? My R is 4.2.2

Thank you in advance.

Kind regards,
Thu

**Comment by thuvousc** [comment]
Hi,

No, I also got problems when installing from GitHub and R Universe. The installation required some dependency packages, but it could not remove prior versions, then it was failed. This problem might be due to the fact I am using my university computer.

> install.packages("remotes")
Installing package into ‘C:/Users/ttmvo/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/remotes_2.4.2.zip'
Content type 'application/zip' length 399278 bytes (389 KB)
downloaded 389 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ttmvo\AppData\Local\Temp\Rtmp6NwkOP\downloaded_packages
> remotes::install_github("https://github.com/ethanbass/chromatographR/")
Downloading GitHub repo ethanbass/chromatographR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                             
 2: CRAN packages only              
 3: None                            
 4: rlang  (1.0.6  -> 1.1.0 ) [CRAN]
 5: cli    (3.4.1  -> 3.6.1 ) [CRAN]
 6: Rcpp   (1.0.9  -> 1.0.10) [CRAN]
 7: utf8   (1.2.2  -> 1.2.3 ) [CRAN]
 8: fansi  (1.0.3  -> 1.0.4 ) [CRAN]
 9: vctrs  (0.5.0  -> 0.6.1 ) [CRAN]
10: tibble (3.1.8  -> 3.2.1 ) [CRAN]
11: dplyr  (1.0.10 -> 1.1.1 ) [CRAN]
12: png    (0.1-7  -> 0.1-8 ) [CRAN]
13: bit    (4.0.4  -> 4.0.5 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
rlang  (1.0.6  -> 1.1.0 ) [CRAN]
cli    (3.4.1  -> 3.6.1 ) [CRAN]
Rcpp   (1.0.9  -> 1.0.10) [CRAN]
utf8   (1.2.2  -> 1.2.3 ) [CRAN]
fansi  (1.0.3  -> 1.0.4 ) [CRAN]
vctrs  (0.5.0  -> 0.6.1 ) [CRAN]
tibble (3.1.8  -> 3.2.1 ) [CRAN]
dplyr  (1.0.10 -> 1.1.1 ) [CRAN]
png    (0.1-7  -> 0.1-8 ) [CRAN]
bit    (4.0.4  -> 4.0.5 ) [CRAN]
Installing 10 packages: rlang, cli, Rcpp, utf8, fansi, vctrs, tibble, dplyr, png, bit
Installing packages into ‘C:/Users/ttmvo/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
    binary source needs_compilation
cli  3.6.0  3.6.1              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/rlang_1.1.0.zip'
Content type 'application/zip' length 1577416 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/cli_3.6.0.zip'
Content type 'application/zip' length 1296260 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/Rcpp_1.0.10.zip'
Content type 'application/zip' length 2812755 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/utf8_1.2.3.zip'
Content type 'application/zip' length 149909 bytes (146 KB)
downloaded 146 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/fansi_1.0.4.zip'
Content type 'application/zip' length 313030 bytes (305 KB)
downloaded 305 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/vctrs_0.6.1.zip'
Content type 'application/zip' length 1337511 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/tibble_3.2.1.zip'
Content type 'application/zip' length 690255 bytes (674 KB)
downloaded 674 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/dplyr_1.1.1.zip'
Content type 'application/zip' length 1553410 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/png_0.1-8.zip'
Content type 'application/zip' length 190849 bytes (186 KB)
downloaded 186 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/bit_4.0.5.zip'
Content type 'application/zip' length 1129531 bytes (1.1 MB)
downloaded 1.1 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘cli’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cli’
Warning: restored ‘cli’
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
Warning: restored ‘Rcpp’
package ‘utf8’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘utf8’
Warning: restored ‘utf8’
package ‘fansi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fansi’
Warning: restored ‘fansi’
package ‘vctrs’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘vctrs’
Warning: restored ‘vctrs’
package ‘tibble’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘tibble’
Warning: restored ‘tibble’
package ‘dplyr’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘dplyr’
Warning: restored ‘dplyr’
package ‘png’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘png’
Warning: restored ‘png’
package ‘bit’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘bit’
Warning: restored ‘bit’

The downloaded binary packages are in
	C:\Users\ttmvo\AppData\Local\Temp\Rtmp6NwkOP\downloaded_packages
-- R CMD build --------------------------------------------------------------------
v  checking for file 'C:\Users\ttmvo\AppData\Local\Temp\Rtmp6NwkOP\remotes661431b018fe\ethanbass-chromatographR-83c136f/DESCRIPTION' ...
-  preparing 'chromatographR': (402ms)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'chromatographR_0.4.7.tar.gz'
   
Installing package into ‘C:/Users/ttmvo/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
'\\home.ansatt.ntnu.no\ttmvo\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'chromatographR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'vctrs' 0.5.0 is already loaded, but >= 0.5.2 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'chromatographR'
* removing 'C:/Users/ttmvo/AppData/Local/R/win-library/4.2/chromatographR'
There were 21 warnings (use warnings() to see them)

Will it work if I use my private computer?

Thank you.

**Comment by ethanbass** [comment]
It seems seems that the computer can’t remove the packages you’re trying to
update. I think this could be a write permissions issue, as in you don’t
have permission to write to your R library on your account. Have you been
able to install other packages on your work computer? You could also try
skipping the updates. It shouldn’t be necessary to have the latest versions
of all those packages for chromatographR to run, but if I’m right about
what the problem is, this won’t work either.

**Comment by thuvousc** [comment]
Yes, you're right. I have no permission to write on the R library. I installed many packages and did not get any errors. It might depend on the dependent packages. I tried installing your packages on my private computer using Github, and it's worked.

Thank you.

**Comment by ethanbass** [comment]
No problem. Glad to hear it's working now! Feel free to open another issue if you run into any further problems
