### ISSUE TITLE
Problem using the filter_peaks function

### ISSUE THREAD

**Issue by jenny-mrchl** [ethanbass/chromatographR#25]
Hi,

I am very beginner regarding in code so maybe this can be solved super easily but I don't know how.
I am currently using your code to analyse chromatograms and it is working pretty well. I want to remove some noisy peaks after doing the peak finding by using the filter_peaks function. 
I think it's working but when I want to plot the filtered chromatograms, I get an error regarding a switch() function that I am not using. I don't understand why I get this issue because I am basically using word for word the code from the description. 

Here is my code : 
pks_gauss_vpdtw <- get_peaks(warp_vpdtw, lambdas = wv, sd.max = 40, fit = "gaussian")

peak_filtration <- filter_peaks(peak_list = pks_gauss_vpdtw,
                                min_height = 0.05)

plot(peak_filtration, chrom_list = Dataset, index=1, lambda=wv)

Error in switch(time.units, min = 1, s = 1/60, ms = 1/60000) :
EXPR must be a length 1 vector

Do you know how I can fix this?

Many thanks

**Comment by ethanbass** [comment]
Hi Jenny,
Thank you for pointing this out! This is in fact a bug. The `filter_peaks` function isn't passing the `time.units` attribute correctly when it's creating the new (filtered) object. I think this should work correctly in the patched version I just uploaded to GitHub. You will need to re-install the package from the master branch and probably restart your R session to make sure it's correctly loaded. Please let me know if it doesn't work.
Ethan

**Comment by jenny-mrchl** [comment]
Dear Ethan,

Thank you very much for your correction! It works exactly how I want!
I really like your package, thanks for your work :)

See you around,

Jenny
