### ISSUE TITLE
stripplot failure in get_peaktable

### ISSUE THREAD

**Issue by BenDMoore** [ethanbass/chromatographR#28]
Hi Ethan,
I'm just getting familiar with your ChromatographR package and am very excited by it, so thanks, but haven't had any luck producing a stripplot with the argument plot_it=T in get_peaktable - most of the striplot code gets written to the console but nothing is plotted...is this a known bug?

**Comment by ethanbass** [comment]
Hi Ben,
Thank you very much for pointing this out. It seems I broke the code for the plot a while ago, but I didn't realize it since I don't use that plot very often. This should be fixed by 53bec5e. I also added a test so I will notice if it breaks again. I think it should work for you now after you reinstall from the master branch (and reset your R session). Let me know!
Ethan

**Comment by BenDMoore** [comment]
Thanks Ethan,
I’ll check that out and let you know
Cheers

Dr Ben Moore, Associate Professor | Ecologist
Hawkesbury Institute for the Environment | Western Sydney University
Hawkesbury Campus (Richmond), Building R2, Room 1.45
Postal address: Locked Bag 1797, Penrith 2751, NSW, Australia
T: +61 (0)2 4570 1384 |M: +61 412 245474
E: ***@***.******@***.***>
Twitter: @blinkybenjy | web: www.uws.edu.au/hie/benmoore

[signature_757244822]


Western Sydney University acknowledges the Darug, Eora, Dharawal and Wiradjuri peoples and thanks them for their support of its work on their lands



From: Ethan Bass ***@***.***>
Reply to: ethanbass/chromatographR ***@***.***>
Date: Wednesday, 30 August 2023 at 12:43
To: ethanbass/chromatographR ***@***.***>
Cc: Ben Moore ***@***.***>, Author ***@***.***>
Subject: [External] Re: [ethanbass/chromatographR] stripplot failure in get_peaktable (Issue #28)


Hi Ben,
Thank you very much for pointing this out. It seems I broke the code for the plot a while ago, but I didn't realize it since I don't use that plot very often. This should be fixed by 53bec5e<https://github.com/ethanbass/chromatographR/commit/53bec5ef75e34d6955cea912496618a692b326ea>. I also added a test so I will notice if it breaks again. I think it should work for you now after you reinstall from the master branch (and reset your R session). Let me know!
Ethan

**Comment by BenDMoore** [comment]
It works!
Thanks – useful plot for someone wanting to reassure themselves about how well get_peaktable works
Ben

From: Ethan Bass ***@***.***>
Reply to: ethanbass/chromatographR ***@***.***>
Date: Wednesday, 30 August 2023 at 12:43
To: ethanbass/chromatographR ***@***.***>
Cc: Ben Moore ***@***.***>, Author ***@***.***>
Subject: [External] Re: [ethanbass/chromatographR] stripplot failure in get_peaktable (Issue #28)


Hi Ben,
Thank you very much for pointing this out. It seems I broke the code for the plot a while ago, but I didn't realize it since I don't use that plot very often. This should be fixed by 53bec5e<https://github.com/ethanbass/chromatographR/commit/53bec5ef75e34d6955cea912496618a692b326ea>. I also added a test so I will notice if it breaks again. I think it should work for you now after you reinstall from the master branch (and reset your R session). Let me know!
Ethan

**Comment by ethanbass** [comment]
Yes, thanks again for pointing this out and glad to hear it's working now!
Ethan
