### ISSUE TITLE
importing cdf (raw) from Waters

### ISSUE THREAD

**Issue by crestre** [ethanbass/chromatographR#29]
I am using a Waters hplc instrument and tried opening their .cdf files - The message that I receive reads "Error in fn(file = file, data_format = data_format, format_out = format_out,  : 
  The `cdf` MS format is not yet supported by an internal `chromConverter` parser.
           Please try the OpenChrom `msd` parser instead."

From you page (https://ethanbass.github.io/chromConverter/) it seems that it might be possible to read Waters .raw files through rainbow. Please could you tell me how would this work?

Just in case I am including a Waters cdf file.

Thanks,
Carla

[Siderophoros AIA1032.zip](https://github.com/ethanbass/chromatographR/files/12506232/Siderophoros.AIA1032.zip)

**Comment by ethanbass** [comment]
Hi Carla,

CDF is a different format than Waters `.raw`. You should be able to parse these files using openchrom parsers. You will need to download Open Chrom (see the instructions in the read me). Then you can try:
`call_openchrom(<path_to_file>, format_in="msd", export_format="mzml")`

Ethan

**Comment by crestre** [comment]
Hi Ethan,
Sorry - I sent an answer to the chromConverter page
