### ISSUE TITLE
Problem trying to preprocess matrix

### ISSUE THREAD

**Issue by tchrisboles** [ethanbass/chromatographR#32]
Pretty much an R newbie here. 
I have a matrix of photodetector intensity versus time in seconds for 12 photodetectors. I wanted to use your package to automate identification of peak times. 

Raw data from one channel looks like this:
![image](https://github.com/ethanbass/chromatographR/assets/33500125/0fdd80ba-d555-4bb0-9067-b3f632904bdb)

I can import the intensity vs time into an R matrix like this:

![image](https://github.com/ethanbass/chromatographR/assets/33500125/47acf407-f58c-408d-8475-cdec09ab4e88)

As recommended in your Introduction, I tried to preprocess the data (since the baseline is NOT constant). However, I get the following error.

![image](https://github.com/ethanbass/chromatographR/assets/33500125/ac872e02-1174-4d92-ace7-edb03c4fa0f9)

The range for time is 0 to 4800 seconds. I set dim1 to values between 600 and 3000 sec where all the peaks occur. And I set dim2 to values between 0.1 to 3 (by=0.01). The complete range for photodetector intensity in the matrix is 0 - 5. I tried other values for dim2 but I still get the error. 

What am I missing?

Or should I skip preprocessing for this data and just jump to find_peaks? Or is your package not suited for my data type?

Thanks.

**Comment by ethanbass** [comment]
Hi,
I'm not sure I understand what you're trying to do with the `new_ph_range` argument. The `dim2` argument is for interpolating across the columns of your matrix. Generally it would make sense to do this only if you have continuous data (e.g., from a diode-array detector). As your data seems to be discontinuous (?) I would suggest using preprocess with the spectral smoothing and column-wise interpolation turned off (e.g., `preprocess(ph_mtrx, dim1=new_ts, spec.smooth=FALSE, interpolate_cols=FALSE)`. Does that make sense?
Ethan

**Comment by tchrisboles** [comment]
Ah, I appear to misunderstand the purpose of preprocessing. I thought preprocessing would fit gaussian curves to my photodetector intensity data in each column, and also flatten the base lines (also columnwise). I don't want to affect the time axis at all, which apparently is what your preprocess is designed for. 

That's what I get for speed reading. 

If I want to identify photodetector peaks columnwise, should I use find_peaks or get_peaks? 

Also, if using find_peaks for my case (x axis = time in seconds, y axis = photodetector intensity (arbitrary units 0-5), what would be the definition of "slope_thresh"? Am I correct that it would be the value of (photodetector signal rise/time) on the rising side of the largest unwanted signal peak in my data?

**Comment by ethanbass** [comment]
The preprocess can do baseline correction as well as other things like
interpolation on either/both axes and/or spectral smoothing. If you want
just baseline correction without anything else, you can do something like:
`preprocess(<matrix or list of matrices>, interpolate_rows = FALSE
interpolate_cols=FALSE, spec.smooth = FALSE)`. This would run baseline
correction (`ptw::baseline.corr`) with the default settings. The vignette
has a little section on how you might go about modifying the parameters for
baseline correction.

For peak identification integration, I'd suggest using the `get_peaks`
function . Under the hood, this runs `find_peaks` and `fit_peaks` to
calculate the areas etc. If you only want the retention times, but don't
want to fit curves to your data (or integrate), you could use `find_peaks`.
However, this function is not vectorized to run on multiple chromatograms
in a list, so you'd have to wrap it in a for loop or an "lapply".

The slope threshold (`slope_thresh`) is the minimum cutoff of the second
derivative of the signal (the slope of the 1st derivative). The method is
cribbed from Tom O'Haver's website on signal processing (
https://terpconnect.umd.edu/~toh/spectrum/Differentiation.html#PeakDetection
&
https://terpconnect.umd.edu/~toh/spectrum/PeakFindingandMeasurement.htm#Derivated-based
peak measurement). Essentially it is a metric of peak width, so you can
remove broad peaks by increasing the value of this parameter.

Ethan

**Comment by tchrisboles** [comment]
Got it. Thanks for your quick reply. I'll play around with it some more. 

I already have find_peaks working pretty well now -- but I'll try the get_peaks routine soon.

Chris

**Comment by ethanbass** [comment]
Sounds good, Chris. Glad to hear it's working! Feel free to open another issue if you run into any further problems.
Ethan
